### ISSUE TITLE
Python3 NoneType error

### ISSUE THREAD

**Issue by icehongssii** [Bittrex/bittrex.github.io#22]
Having an NoneType Error, I just simply run the python example code in this repo without any modifying.
Here is the error that I am getting. Anyone has same issue?

`Traceback (most recent call last):
  File "bi1.py", line 81, in <module>
    hub.server.invoke('SubscribeToSummaryDeltas')  # Invoke 1
  File "/home/jeil/.local/lib/python3.5/site-packages/signalr/hubs/_hub.py", line 23, in invoke
    'I': self.__connection.increment_send_counter()
  File "/home/jeil/.local/lib/python3.5/site-packages/signalr/_connection.py", line 63, in send
    self.__transport.send(data)
  File "/home/jeil/.local/lib/python3.5/site-packages/signalr/transports/_auto_transport.py", line 31, in send
    self.__transport.send(data)
AttributeError: 'NoneType' object has no attribute 'send'` 
`

**Comment by slazarov** [comment]
Runs perfectly on a clean venv with only the signalr client installed:
```python
pip install git+https://github.com/slazarov/python-signalr-client.git
```
